![imagen](./img/ejercicios.png)

In [1]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [88]:
my_array = np.arange(10)
my_array
print (my_array [::-2])

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [17]:
print(my_array)
print (my_array [8:6:-1])

[0 1 2 3 4 5 6 7 8 9]
[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [21]:
print(my_array)
print (my_array [2::-1])

[0 1 2 3 4 5 6 7 8 9]
[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [29]:
matriz_ex4 = np.arange(1, 21).reshape(4, 5)
matriz_ex4
print(matriz_ex4)
print ()
matriz_ex4_invertida = matriz_ex4[::-1, ::-1]
print(matriz_ex4_invertida)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [56]:
print(matriz_ex4[0:2,0:2])

[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [73]:
matriz_ex4
print(matriz_ex4)
print()
print(matriz_ex4[0::2,0::2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [85]:
matriz_ex4
print(matriz_ex4)
print()
print(matriz_ex4[0:3:1,::-1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [100]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

In [87]:
print(x[0::3])

['Loro' 'Loro']


In [109]:
loros = np.where(x == "Loro", x, '0')
loros = loros[loros != '0']  # Eliminar los valores "0"
print (x)
print(loros)

['Loro' 'Perro' 'Gato' 'Loro' 'Perro']
['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [127]:
sec_ex_9 = np.arange(20)
print(sec_ex_9)
print()
sec_ex_9_v1 = sec_ex_9.reshape(10,2)
print(sec_ex_9_v1)
print()
sec_ex_9_v2 = np.split(sec_ex_9_v1, [5,2])
print(sec_ex_9_v2)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]

[array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]]), array([], shape=(0, 2), dtype=int64), array([[ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])]


In [126]:
# Crear una secuencia de 20 elementos
secuencia = np.arange(1, 21)

# Transformar en un array compuesto por 2 matrices de 5x2
resultado = secuencia.reshape(2, 5, 2)

print(resultado)

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]
  [15 16]
  [17 18]
  [19 20]]]


## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [139]:
# Crear un array de 10 ceros
array = [0] * 10

np.size(array)
print(f'bits de array en memoria: {np.size(array)}')

array[3] = 1

print(array)



bits de array en memoria: 10
[0, 0, 0, 1, 0, 0, 0, 0, 0, 0]


## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [142]:
vector = np.arange(10, 50)
print(vector)
print()
vector_invertido = vector[::-1]
print(vector_invertido)



[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [143]:
vector_ex_12 = [1,2,0,0,4,0]

In [144]:
np.nonzero(vector_ex_12)[0]

array([0, 1, 4])

## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [147]:
matriz_ex_13 = np.random.random((10, 10))

valor_min = np.min(matriz_ex_13)
valor_max = np.max(matriz_ex_13)

print(matriz_ex_13)
print(valor_min)
print(valor_max)

[[0.50403256 0.51081648 0.68416328 0.13787709 0.22862893 0.3335318
  0.8073474  0.50285147 0.23911197 0.84000804]
 [0.70842901 0.88148764 0.91276811 0.61487762 0.78955045 0.3234682
  0.90399292 0.52030847 0.48535675 0.22347646]
 [0.93522229 0.72371862 0.315745   0.22886151 0.3307889  0.76958023
  0.80824955 0.87254448 0.66981083 0.448569  ]
 [0.85502293 0.9947288  0.74285268 0.58483578 0.04717349 0.78810094
  0.25806989 0.16839566 0.84836545 0.21882144]
 [0.23685165 0.74866044 0.25395847 0.25071114 0.21761029 0.29752909
  0.67849045 0.10229241 0.77493922 0.4018154 ]
 [0.12725629 0.32937749 0.41135201 0.05849195 0.99131915 0.41288973
  0.92140743 0.68580277 0.53433591 0.50263811]
 [0.68037211 0.90007316 0.39257291 0.78456338 0.24746592 0.31019971
  0.07031501 0.21593937 0.60930595 0.30579714]
 [0.64435584 0.70008484 0.72245382 0.69258807 0.24464673 0.9556266
  0.79711149 0.89945368 0.64054906 0.66201347]
 [0.77574924 0.75320166 0.21244793 0.85514617 0.88648197 0.55441271
  0.34344323 0.

## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

In [154]:
vector_ex_14 = np.random.random(30)
media = np.mean(vector_ex_14)

print(vector_ex_14)
print()
print(media)


[0.85780674 0.2910023  0.65424775 0.75473099 0.02025356 0.65128593
 0.8953517  0.84668162 0.82874888 0.95528174 0.21846178 0.72758061
 0.61534553 0.63644687 0.30929664 0.8469565  0.08930968 0.12459973
 0.69910011 0.6367245  0.4277596  0.83139914 0.70446603 0.23307699
 0.15561397 0.60052268 0.67242091 0.00463068 0.21982297 0.73402541]

0.5414317183371185


## Ejercicio 15
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [160]:

def crear_matriz_con_borde(dimension):
    # Crear una matriz de ceros de tamaño 'dimension x dimension'
    matriz = np.zeros((dimension, dimension), dtype=int)
    
    # Establecer el borde de la matriz con unos
    matriz[0, :] = 1  # Fila superior
    matriz[-1, :] = 1  # Fila inferior
    matriz[:, 0] = 1  # Columna izquierda
    matriz[:, -1] = 1  # Columna derecha
    
    return matriz

# Ejemplo de uso con una matriz de 6x6
dimension = 4
matriz_borde = crear_matriz_con_borde(dimension)

print("Matriz con borde de 1s:\n", matriz_borde)

Matriz con borde de 1s:
 [[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


## Ejercicio 16
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [161]:
# Crear una matriz de 8x8 de ceros
matriz = np.zeros((8, 8), dtype=int)

# Rellenar la matriz alternando 0s y 1s
matriz[1::2, ::2] = 1  # Rellenar filas impares con 1s en columnas pares
matriz[::2, 1::2] = 1  # Rellenar filas pares con 1s en columnas impares

print(matriz)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 17
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [162]:
# Crear un patrón básico 2x2
patron = np.array([[0, 1], [1, 0]])

# Replicar el patrón usando np.tile para crear una matriz de 8x8
matriz = np.tile(patron, (4, 4))

print(matriz)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [163]:
# Crear una matriz aleatoria de 5x5
matriz = np.random.random((5, 5))

# Calcular la media y desviación estándar de la matriz
media = np.mean(matriz)
desviacion_estandar = np.std(matriz)

# Normalizar la matriz
matriz_normalizada = (matriz - media) / desviacion_estandar

print("Matriz original:\n", matriz)
print("\nMatriz normalizada:\n", matriz_normalizada)

Matriz original:
 [[0.35471898 0.47235097 0.26472769 0.4099562  0.92826344]
 [0.38953622 0.48076384 0.24626318 0.23978575 0.20472144]
 [0.06644769 0.45807267 0.16452995 0.15550291 0.04913043]
 [0.79117443 0.23989551 0.06029717 0.12778035 0.90352081]
 [0.79745676 0.02389471 0.3572094  0.96382039 0.10381007]]

Matriz normalizada:
 [[-0.05376524  0.35621816 -0.36741233  0.13875336  1.9452123 ]
 [ 0.0675835   0.3855396  -0.43176678 -0.45434261 -0.57655242]
 [-1.05847865  0.30645395 -0.71663204 -0.74809403 -1.11883458]
 [ 1.46741522 -0.45396006 -1.0799151  -0.84471562  1.85897668]
 [ 1.48931107 -1.20678878 -0.04508534  2.06913911 -0.92825936]]


## Ejercicio 19
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [164]:
# Crear una secuencia de números del 0 al 10
secuencia = np.arange(11)
print("Secuencia original:\n", secuencia)

Secuencia original:
 [ 0  1  2  3  4  5  6  7  8  9 10]


In [165]:
# Crear una copia de la secuencia original
array_modificado = secuencia.copy()

# Sustituir por -1 los valores entre 3 y 8
array_modificado[(array_modificado >= 3) & (array_modificado <= 8)] = -1
print("\nArray modificado (valores entre 3 y 8 cambiados a -1):\n", array_modificado)


Array modificado (valores entre 3 y 8 cambiados a -1):
 [ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]


In [166]:
# Crear una copia de la secuencia original para negación
array_negado = secuencia.copy()

# Negar los valores entre 3 y 8 (sólo si son enteros, con multiplicación por -1)
array_negado[(array_negado >= 3) & (array_negado <= 8)] *= -1
print("\nArray con valores negados entre 3 y 8:\n", array_negado)


Array con valores negados entre 3 y 8:
 [ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]
